v: 3

# a file used to persist the state of the controller. The folder must already exist when the controller starts.
db:               db/ctrl.db

identity:
  cert:           pki/certs/controller-client.cert
  server_cert:    pki/certs/controller-server.cert
  key:            pki/keys/controller-server.key
  ca:             pki/certs/controller-server.chain.pem


# the endpoint that routers will connect to the controller over.
ctrl:
  listener:             tls:127.0.0.1:6262

# the endpoint that management tools connect to the controller over.
mgmt:
  listener:             tls:127.0.0.1:10000

# By having an 'edge' section defined, the ziti-controller will attempt to parse the edge configuration. Removing this
# section, commenting out, or altering the name of the section will cause the edge to not run.
edge:
  # This section represents the configuration of the Edge API that is served over HTTPS
  api:
    # (required) The interface and port that the Edge API should be served on.
    listener:  127.0.0.1:1280
    # (required) The host/port combination that is reported as publicly accessible for the Edge API
    advertise: localhost:1280
    # (optional, defaults to 10) The number of minutes before an Edge API session will timeout. Timeouts are reset by
    # API requests and connections that are maintained to Edge Routers
    sessionTimeoutMinutes: 30
    #(optional, defaults to the root identity) An alternate "identity" to use for the Edge API. If this section is not
    # defined the root identity section will be used. This is useful for situations where Edge API will present a
    # publicly signed certificate instead of one generated by a private PKI created by ziti pki create
#    identity:
#      ca:          pki/certs/edge-router.cert
#      server_key:  pki/keys/edge-router-server.key
#      server_cert: pki/certs/edge-router-server.cert


  # This section is used to define option that are used during enrollment of Edge Routers, Ziti Edge Identities.
  enrollment:
    # (required) A Ziti Identity configuration section that specifically makes use of the cert and key fields to define
    # a signing certificate from the PKI that the Ziti environment is using to sign certificates. The CA is used to
    # specify the chain that should be added to the /.well-known CA store that is used to bootstrap trust with the
    # Ziti Controller. This chain should be from intermediate to root and can contain multiple chains if necessary.
    signingCert:
      cert: pki/certs/signing.cert
      key:  pki/keys/signing.key
      ca:   pki/certs/signing.chain.pem
    edgeIdentity:
      # (optional, defaults to 5) The length of time that a Ziti Edge Identity enrollment should remain valid. After
      # this duration, the enrollment will expire and not longer be usable.
      durationMinutes: 5
    edgeRouter:
      # (optional, defaults to 5) The length of time that a Ziti Edge Router enrollment should remain valid. After
      # this duration, the enrollment will expire and not longer be usable.
      durationMinutes: 5
  persistence:
    # See  documentation:
    # - https://godoc.org/github.com/lib/pq
    # - https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
    # (required) A Postgres connection string used to connect to a database
    connectionUrl: postgres://postgres:your_db_pwd_here@your_postgres_host/postgres?sslmode=disable
    # (required) The Postgres database name to use
    dbName: postgres
